# Generated by Django 4.0.6 on 2022-07-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_num', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('type', models.CharField(choices=[('Components', (('cpu', 'Процессор'), ('motherboard', 'Материнская плата'), ('gpu', 'Видеокарта'))), ('Periphery', (('mouse', 'Мышь'),))], max_length=50)),
            ],
        ),
    ]
