# Generated by Django 4.0.6 on 2022-07-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='article_num',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='good',
            name='type',
            field=models.CharField(choices=[('Комплектующие ПК', (('cpu', 'CPU'), ('motherboard', 'материнская плата'), ('gpu', 'GPU'), ('ram', 'RAM'))), ('Периферийные устройства', (('mouse', 'мышь'), ('keyboard', 'клавиатура')))], max_length=30),
        ),
    ]
